### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by rtm** [thisables/curry#35]
Could someone give me a quick run-down on how the tests are structured, specifically why we have `es5.js` and `es-2016.js`?

**Comment by davidchase** [comment]
Also curious about the naming of the files they tests do seem different but the naming throws me off

also any thoughts on [ava](https://github.com/sindresorhus/ava) test framework? we started using it at work very nice :+1:

**Comment by stoeffel** [comment]
Sorry guys for me unresponsiveness this week. Was in bed :mask: 

The `es5` tests are transpiled and the `es-2016` tests aren't.
I actually don't see why we need both. The only reason why there are two test files is, that @tomekwi and I where creating the tests at the same time.

> also any thoughts on ava test framework?

I started using ava too lately. It's looks great. I'm open to refactor all the tests and use ava.

**Comment by tomek-he-him** [comment]
Actually, we initially had two APIs.

One for ES 2015: `import curry from 'curry-this/module'`

and a bring-your-own-symbol-polyfill ES5 one: `var curry = require('curry-this')({symbol: function () {return {};}})`.

Now it’s no longer relevant.
